name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Install Lint & Format Tools
      run: |
        pip install flake8 black

    - name: Run flake8 (Lint)
      run: flake8 .

    - name: Check code format with black
      run: black --check .

    - name: Check Docker Versions
      run: |
        docker --version
        docker compose version

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}
        password: ${{ secrets.DOCKERHUB_TOKEN_LOOKKAEW  }}

    - name: Build & Push Docker Images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-worker:latest ./worker
        docker build -t ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-scheduler:latest ./scheduler
        docker build -t ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-web:latest ./web

        docker push ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-worker:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-scheduler:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME_LOOKKAEW }}/autoperf-web:latest